import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Heart, 
  Frown, 
  Zap, 
  Users, 
  Sparkles, 
  Copy, 
  Check, 
  RefreshCw, 
  Share2, 
  PenTool,
  History,
  Quote,
  Library
} from 'lucide-react';
import { generateShayari, getRandomFromDataset } from './services/geminiService';
import { cn } from './lib/utils';

interface Shayari {
  hindi: string;
  romanized: string;
  meaning: string;
  category: string;
  timestamp: number;
  author?: string;
}

const CATEGORIES = [
  { id: 'love', label: 'Ishq (Love)', icon: Heart, color: 'text-rose-500' },
  { id: 'sad', label: 'Dard (Sad)', icon: Frown, color: 'text-blue-500' },
  { id: 'motivation', label: 'Zazba (Motivation)', icon: Zap, color: 'text-amber-500' },
  { id: 'friendship', label: 'Dosti (Friendship)', icon: Users, color: 'text-emerald-500' },
  { id: 'life', label: 'Zindagi (Life)', icon: Sparkles, color: 'text-purple-500' },
];

export default function App() {
  const [category, setCategory] = useState('love');
  const [customTheme, setCustomTheme] = useState('');
  const [loading, setLoading] = useState(false);
  const [currentShayari, setCurrentShayari] = useState<Shayari | null>(null);
  const [history, setHistory] = useState<Shayari[]>([]);
  const [copied, setCopied] = useState(false);
  const [showHistory, setShowHistory] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const theme = customTheme || CATEGORIES.find(c => c.id === category)?.label || 'General';
      const result = await generateShayari(theme, category);
      const newShayari: Shayari = {
        ...result,
        category,
        timestamp: Date.now()
      };
      setCurrentShayari(newShayari);
      setHistory(prev => [newShayari, ...prev].slice(0, 10));
    } catch (error) {
      console.error("Failed to generate:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleDiscover = () => {
    const result = getRandomFromDataset(category);
    const newShayari: Shayari = {
      ...result,
      timestamp: Date.now()
    };
    setCurrentShayari(newShayari);
    setHistory(prev => [newShayari, ...prev].slice(0, 10));
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const shareShayari = () => {
    if (!currentShayari) return;
    const text = `${currentShayari.hindi}\n\n(${currentShayari.romanized})\n\nGenerated by Kavita AI`;
    if (navigator.share) {
      navigator.share({
        title: 'Kavita AI Shayari',
        text: text,
      });
    } else {
      copyToClipboard(text);
    }
  };

  return (
    <div className="min-h-screen bg-paper selection:bg-gold/30">
      {/* Background Decorative Elements */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden opacity-20">
        <div className="absolute -top-24 -left-24 w-96 h-96 bg-gold/20 rounded-full blur-3xl" />
        <div className="absolute top-1/2 -right-24 w-64 h-64 bg-olive/20 rounded-full blur-3xl" />
      </div>

      <header className="relative pt-12 pb-8 px-6 text-center max-w-4xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <h1 className="text-5xl md:text-7xl font-serif font-bold tracking-tight text-ink mb-4">
            Kavita <span className="text-gold italic">AI</span>
          </h1>
          <p className="text-lg md:text-xl text-olive font-serif italic max-w-2xl mx-auto">
            "Shabdon ka sangam, jazbaaton ki zubaan"
          </p>
        </motion.div>
      </header>

      <main className="relative max-w-4xl mx-auto px-6 pb-24">
        {/* Controls Section */}
        <section className="mb-12">
          <div className="flex flex-wrap justify-center gap-3 mb-8">
            {CATEGORIES.map((cat) => (
              <button
                key={cat.id}
                onClick={() => setCategory(cat.id)}
                className={cn(
                  "flex items-center gap-2 px-4 py-2 rounded-full border transition-all duration-300 cursor-pointer",
                  category === cat.id 
                    ? "bg-ink text-paper border-ink shadow-lg scale-105" 
                    : "bg-white/50 text-ink border-gold/30 hover:border-gold hover:bg-white"
                )}
              >
                <cat.icon className={cn("w-4 h-4", category === cat.id ? "text-paper" : cat.color)} />
                <span className="text-sm font-medium">{cat.label}</span>
              </button>
            ))}
          </div>

          <div className="relative max-w-lg mx-auto mb-8">
            <div className="absolute inset-y-0 left-4 flex items-center pointer-events-none">
              <PenTool className="w-5 h-5 text-gold/60" />
            </div>
            <input
              type="text"
              placeholder="Or enter your own theme (e.g. Rainy night, First meeting)..."
              value={customTheme}
              onChange={(e) => setCustomTheme(e.target.value)}
              className="w-full pl-12 pr-4 py-4 bg-white/80 border border-gold/20 rounded-2xl focus:outline-none focus:ring-2 focus:ring-gold/50 focus:border-transparent transition-all shadow-sm font-serif text-lg"
            />
          </div>

          <div className="flex flex-col sm:flex-row justify-center gap-4">
            <button
              onClick={handleGenerate}
              disabled={loading}
              className="group relative px-8 py-4 bg-gold text-paper rounded-2xl font-bold text-lg shadow-xl hover:shadow-gold/20 hover:-translate-y-1 transition-all disabled:opacity-50 disabled:translate-y-0 cursor-pointer"
            >
              <span className="flex items-center gap-2">
                {loading ? (
                  <RefreshCw className="w-5 h-5 animate-spin" />
                ) : (
                  <Sparkles className="w-5 h-5" />
                )}
                {loading ? "Kalam chal rahi hai..." : "AI Generate"}
              </span>
            </button>
            
            <button
              onClick={handleDiscover}
              disabled={loading}
              className="group relative px-8 py-4 bg-ink text-paper rounded-2xl font-bold text-lg shadow-xl hover:shadow-ink/20 hover:-translate-y-1 transition-all disabled:opacity-50 disabled:translate-y-0 cursor-pointer"
            >
              <span className="flex items-center gap-2">
                <Library className="w-5 h-5" />
                Discover Classic
              </span>
            </button>
          </div>
        </section>

        {/* Display Section */}
        <div className="min-h-[400px]">
          <AnimatePresence mode="wait">
            {currentShayari ? (
              <motion.div
                key={currentShayari.timestamp}
                initial={{ opacity: 0, scale: 0.95, y: 20 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95, y: -20 }}
                className="relative bg-white border border-gold/10 rounded-3xl p-8 md:p-12 shadow-2xl overflow-hidden"
              >
                {/* Decorative Quote Icons */}
                <Quote className="absolute top-8 left-8 w-12 h-12 text-gold/10 -rotate-12" />
                <Quote className="absolute bottom-8 right-8 w-12 h-12 text-gold/10 rotate-168" />

                <div className="relative z-10 text-center">
                  <div className="mb-8">
                    <h2 className="text-3xl md:text-4xl font-serif font-bold text-ink leading-relaxed whitespace-pre-line">
                      {currentShayari.hindi}
                    </h2>
                    {currentShayari.author && (
                      <p className="mt-4 text-gold font-serif italic">— {currentShayari.author}</p>
                    )}
                  </div>
                  
                  <div className="mb-8 py-4 border-y border-gold/10">
                    <p className="text-lg md:text-xl text-olive font-serif italic leading-relaxed">
                      {currentShayari.romanized}
                    </p>
                  </div>

                  <div className="mb-10">
                    <p className="text-sm uppercase tracking-widest text-gold font-bold mb-2">Meaning</p>
                    <p className="text-ink/70 max-w-xl mx-auto italic">
                      {currentShayari.meaning}
                    </p>
                  </div>

                  <div className="flex justify-center gap-4">
                    <button
                      onClick={() => copyToClipboard(currentShayari.hindi)}
                      className="flex items-center gap-2 px-6 py-3 rounded-xl bg-paper border border-gold/20 hover:border-gold transition-all text-ink font-medium cursor-pointer"
                    >
                      {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
                      {copied ? "Copied" : "Copy Hindi"}
                    </button>
                    <button
                      onClick={shareShayari}
                      className="flex items-center gap-2 px-6 py-3 rounded-xl bg-paper border border-gold/20 hover:border-gold transition-all text-ink font-medium cursor-pointer"
                    >
                      <Share2 className="w-4 h-4" />
                      Share
                    </button>
                  </div>
                </div>
              </motion.div>
            ) : (
              !loading && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="flex flex-col items-center justify-center py-20 text-olive/40"
                >
                  <History className="w-16 h-16 mb-4 stroke-1" />
                  <p className="text-xl font-serif italic">Select a theme and let the magic begin</p>
                </motion.div>
              )
            )}
          </AnimatePresence>
        </div>

        {/* History Toggle */}
        {history.length > 0 && (
          <div className="mt-12">
            <button
              onClick={() => setShowHistory(!showHistory)}
              className="flex items-center gap-2 mx-auto text-gold hover:text-olive transition-colors font-medium cursor-pointer"
            >
              <History className="w-4 h-4" />
              {showHistory ? "Hide History" : "Show Recent Shayaris"}
            </button>

            <AnimatePresence>
              {showHistory && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  exit={{ opacity: 0, height: 0 }}
                  className="mt-6 space-y-4 overflow-hidden"
                >
                  {history.map((item) => (
                    <div
                      key={item.timestamp}
                      onClick={() => setCurrentShayari(item)}
                      className="bg-white/50 border border-gold/10 p-4 rounded-2xl cursor-pointer hover:bg-white hover:shadow-md transition-all group"
                    >
                      <div className="flex justify-between items-start">
                        <p className="text-ink font-serif line-clamp-1">{item.hindi}</p>
                        <span className="text-[10px] uppercase tracking-tighter text-gold font-bold">
                          {CATEGORIES.find(c => c.id === item.category)?.label || 'Classic'}
                        </span>
                      </div>
                    </div>
                  ))}
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        )}
      </main>

      <footer className="py-12 px-6 text-center border-t border-gold/10">
        <p className="text-olive/60 font-serif italic">
          Crafted with ❤️ for the lovers of poetry
        </p>
      </footer>
    </div>
  );
}
